resources:
  - type: js
    url: /local/monster-card.js
  - type: module
    url: /local/mini-media-player-bundle.js?v=0.9.5
title: Home
views:
  - cards:
      - card:
          title: Motion Detected
          type: entities
          entities:
            - entity: binary_sensor.door_window_sensor_158d0002133b59
            - entity: binary_sensor.front_door_camera_online
            - entity: binary_sensor.motion_sensor_158d0001a92381
            - entity: binary_sensor.motion_sensor_158d0001e55662
            - entity: binary_sensor.octoprint_printing
        filter:
          include:
            - domain: binary_sensor
              state: 'on'
        show_empty: true
        type: 'custom:monster-card'
      - card:
          title: Lights On
          type: entities
          entities:
            - entity: light.hallway_3
            - entity: light.kitchen1
            - entity: light.kitchen2
            - entity: light.rode_lamp
            - entity: light.tradfri_bulb_e27_w_opal_1000lm_2
            - entity: light.tradfri_bulb_gu10_w_400lm_11
            - entity: light.tradfri_bulb_gu10_w_400lm_12
        filter:
          include:
            - domain: light
              state: 'on'
        show_empty: true
        type: 'custom:monster-card'
      - card:
          title: Currently playing
          type: entities
          entities:
            - entity: media_player.livingroom_
        filter:
          exclude:
            - entity_id: media_player.spotify
          include:
            - domain: media_player
              state: playing
        show_empty: true
        type: 'custom:monster-card'
        show_header_toggle: false
      - card:
          title: Climate
          type: entities
          entities:
            - entity: climate.kleine_kamer
            - entity: climate.slaapkamer
            - entity: climate.voorkamer
            - entity: climate.woonkamer
        filter:
          include:
            - domain: climate
        type: 'custom:monster-card'
      - cards:
          - entity: camera.voordeur
            show_name: false
            show_state: false
            type: picture-entity
          - entity: camera.zijdeur
            show_name: false
            show_state: false
            type: picture-entity
          - entity: camera.front_door
            show_name: false
            show_state: false
            type: picture-entity
        type: vertical-stack
      - entities:
          - entity: media_player.bedroom_speaker
            group: true
            type: 'custom:mini-media-player'
          - entity: media_player.living_room_speaker
            group: true
            type: 'custom:mini-media-player'
          - entity: media_player.old_speaker
            group: true
            type: 'custom:mini-media-player'
          - entity: media_player.upstairs_speaker
            group: true
            type: 'custom:mini-media-player'
          - entity: media_player.googlehomehub2919
            group: true
        title: Media Players
        type: entities
      - entities:
          - artwork: cover
            entity: media_player.livingroom_
            group: true
            type: 'custom:mini-media-player'
          - artwork: cover
            entity: media_player.party
            group: true
            power_color: true
            type: 'custom:mini-media-player'
          - artwork: cover
            entity: media_player.upstairs
            group: true
            type: 'custom:mini-media-player'
        title: Media Player Groups
        type: entities
      - artwork: cover
        entity: media_player.spotify
        media_buttons:
          - name: Easy on Sunday
            type: playlist
            url: 'spotify:user:spotify:playlist:37i9dQZF1DWZpGSuzrdTXg'
          - name: Joost New Releases
            type: playlist
            url: 'spotify:user:foost:playlist:7JLymXyQVjbeupuaapu95L'
          - name: De Yaylist
            type: playlist
            url: 'spotify:user:faberyayo:playlist:4I0NnAhaMaPcynq0xbLdyL'
        name: Spotify player
        show_source: full
        type: 'custom:mini-media-player'
    title: Home
  - cards:
      - entities:
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_actual_tool0_temp
          - sensor.octoprint_current_state
          - sensor.octoprint_job_percentage
          - sensor.octoprint_target_bed_temp
          - sensor.octoprint_target_tool0_temp
          - sensor.octoprint_time_elapsed_format
          - sensor.octoprint_time_remaining_format
        type: entities
      - entity: camera.ffmpeg
        show_name: false
        show_state: false
        type: picture-entity
      - entities: []
        show_header_toggle: true
        title: 3d printer light
        type: entities
    icon: 'mdi:printer-3d'
    title: 3d printer
  - cards:
      - type: entities
        entities:
          - entity: light.tradfri_bulb_e27_w_opal_1000lm_2
          - entity: light.window_light
          - entity: light.rode_lamp
        show_header_toggle: true
        title: Livingroom_group
      - type: entities
        entities:
          - entity: cover.livingroom_roller
        title: Blinds
    title: Livingroom
  - badges: []
    cards:
      - entities:
          - entity: light.bathroom1
          - entity: light.bathroom2
          - entity: light.bathroom3
        show_header_toggle: true
        title: Bathroom lights
        type: entities
    icon: ''
    title: Bathroom
  - cards:
      - entities:
          - entity: light.kitchen1
          - entity: light.kitchen2
          - entity: light.kitchen_ledstrip
        show_header_toggle: true
        title: Kitchen
        type: entities
    title: Kitchen
  - cards:
      - type: entities
        entities:
          - entity: cover.office_roller
        title: Blinds
        show_header_toggle: false
      - type: entities
        entities:
          - entity: light.falcon_light
          - entity: light.officeleft
          - entity: light.officeright
    badges: []
    title: Office
    icon: ''
